/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/relevant-remand/{prisonerId}': {
    /**
     * Calculates relevant remand
     * @description This endpoint will calculate relevant remand based on the data from NOMIS before returning it to the user
     */
    post: operations['calculate']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    Remand: {
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      /** Format: int32 */
      sentence: number
      /** Format: int64 */
      days: number
    }
    RemandPeriod: {
      /** Format: date */
      from: string
      /** Format: date */
      to: string
      /** Format: date */
      offenceDate: string
      /** Format: date */
      offenceEndDate?: string
      offenceCode: string
      offenceDescription: string
      courtCaseRef?: string
      /** Format: int64 */
      chargeId: number
      /** Format: int64 */
      days: number
    }
    RemandResult: {
      remandPeriods: components['schemas']['RemandPeriod'][]
      finalRemand: components['schemas']['Remand'][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  calculate: {
    /**
     * Calculates relevant remand
     * @description This endpoint will calculate relevant remand based on the data from NOMIS before returning it to the user
     */
    parameters: {
      /**
       * @description The prisoners ID (aka nomsId)
       * @example A1234AB
       */
      path: {
        prisonerId: string
      }
    }
    responses: {
      /** @description Returns calculated relevant remand */
      200: {
        content: {
          'application/json': components['schemas']['RemandResult']
        }
      }
      /** @description Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['RemandResult']
        }
      }
      /** @description Forbidden, requires an appropriate role */
      403: {
        content: {
          'application/json': components['schemas']['RemandResult']
        }
      }
    }
  }
}
