---
# Per environment values which override defaults in hmpps-manage-a-warrant-folder/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-a-warrant-folder-dev.hmpps.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    INGRESS_URL: "https://manage-a-warrant-folder-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    WARRANT_FOLDER_URL: "https://manage-a-warrant-folder-api-dev.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://api-dev.prison.service.justice.gov.uk"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

